vae:
  enc_latent_size: 256
  enc_kernel_size: 3
  dec_kernel_size: 4
  stride: 2
  pad: 1
loss:
  loss_type: rssm
  image_loss: mse
  recon_mult: 1000.0
  beta: 0.0001
  lambda: 0.0005
  kld_anneal_mode: linear
trans:
  stochastic_size: 16
  deterministic_size: 256
  past_length: 3
  pred_length: 3
  alpha: 0.0003
  weight_decay: 0.0001
train:
  dataset: push_1k
  batch_size: 128
  num_epochs: 500
  device: cuda:0
  render: false
  save: true
  eval: true
  plot_freq: 10000
  train_ratio: 0.9
  load_path: null
  eval_only: true
closed_loop:
  closed_loop: true
  policy: informative
  epochs_warmup: 1
  num_rollout_steps: 50
  plan_horizon: 12
  num_batches: 100
  buffer_capacity: 2000
  samples: 30
  elite_frac: 0.1
  iters: 3
  init_control: random
  sigma_init: 0.3
  sigma_min: 0.05
  alpha: 0.7
config_name: push_active_17
load_path: runs/push/trained
env_interactions: 25000
train_interactions: 6400000
runtime: 03:20:46