#
# Config file reacher RSSMPretrainer with uncertainty loss and RSSM transition model
#
# Encoder/Decoder
vae:
  enc_latent_size: 256
  enc_kernel_size: 3
  dec_kernel_size: 4
  stride: 2
  pad: 1
# Loss hyperparams
loss:
  loss_type: rssm         # Loss type to use: mse | uncertainty  # TODO: Change this setup for rssm
  recon_mult: !!float 1e4           # MSE Reconstruction loss multiplier
  beta: !!float 1e-4                # Standard Gaussian KL multiplier
  lambda: !!float 1e-4              # Transition KL multiplier
  kld_anneal_mode: linear           # Beta annealing mode: const | linear
# Transition model hyperparams
trans:
  stochastic_size: 4                # Stochastic state model latent dim
  deterministic_size: 128             # Deterministic state model latent dim
  past_length: 1                    # Length of image history passed into encoder
  pred_length: 3                    # Length of image prediction horizon
  alpha: !!float 1e-4               # Learning rate
  weight_decay: !!float 1e-4        # Adam optimizer weight decay
# Training settings
train:
  dataset: reacher_510k      # Which dataset to use for training (in data/)
  batch_size: 32
  num_epochs: 30
  device: cuda:2             # cpu | cuda:0 | cuda:1 | cuda:2
  render: False              # Whether to render live interactive training plot, or simply save after training is finished
  save: True                 # Whether to save final trained model and training plot
  eval: True                 # Whether to eval model performance immediately after training
  plot_freq: 10000           # Frequency to update the plot, in timesteps
  train_ratio: 0.9           # Ratio of dataset to use for training
  load_path:                 # Path to load model from (for resuming training or eval only)    
# Policy settings for training closed loop
closed_loop: 
  closed_loop: False                 # Whether to use closed loop training
  policy: random               # What type of policy to use: conv | random | uncertainty
    
